spring:
  application:
    name: Server

  datasource:
    username: root
    password: zhanghai2
    url: jdbc:mysql://127.0.0.1:3306/college_poi
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8020